"""
russell2500_tickers.py -- static snapshot of the Russell 2500 (small/mid-cap)
constituent list, used to broaden backtest_early_trend.py's universe beyond
the S&P 500 -- Early Trend is meant to catch a stock BEFORE it's big, but
S&P 500 membership is a lagging signal of a company already having gotten
big, so backtesting only against S&P 500 constituents biases the sample
toward exactly the population this screen isn't trying to find.

No free, redistributable official Russell constituent list exists (FTSE
Russell licenses that data). This is reconstructed from two free, public
sources: iShares publishes full daily holdings for its Russell-tracking ETFs
as downloadable files (a regulatory transparency requirement for exchange-
traded funds, not something Russell/FTSE controls) --
  - SMMD (iShares Russell 2500 ETF): direct holdings, ~2,470 equities
  - IWM (iShares Russell 2000 ETF): ~1,960 equities, largely a subset of SMMD
Union of both (excluding SMMD's own IWM position and non-equity/placeholder
rows) gives this list. Fetched via each fund's public holdings-download
endpoint:
  https://www.blackrock.com/varnish-api/blk-one01-product-data/product-data/api/v1/get-fund-document
  ?appType=PRODUCT_PAGE&appSubType=ISHARES&targetSite=us-ishares&locale=en_US
  &portfolioId={239710 for IWM, 288024 for SMMD}&component=fundDownload&userType=individual

Snapshot date: 2026-08-18. Like sp500_tickers.py, this is a POINT-IN-TIME
snapshot, not historical membership -- a stock backtest_early_trend.py is
walking 3 years of history for may have graduated INTO the S&P 500 (and thus
OUT of today's Russell 2500) since then, or fallen out of the index
entirely. That's an accepted limitation shared with sp500_tickers.py, not
something this snapshot can fix; no free source gives point-in-time-correct
historical index membership. Refresh by re-running the same two downloads
and re-deriving the union.
"""

RUSSELL2500_TICKERS = [
    "AA", "AAL", "AAMI", "AAOI", "AAON", "AAP", "AAT", "ABAT", "ABCB", "ABEO",
    "ABG", "ABM", "ABOS", "ABR", "ABSI", "ABUS", "ABX", "ACA", "ACAD", "ACCO",
    "ACDC", "ACEL", "ACH", "ACHC", "ACHR", "ACHV", "ACI", "ACIC", "ACIW", "ACLS",
    "ACM", "ACMR", "ACNB", "ACR", "ACRE", "ACRS", "ACT", "ACTG", "ACU", "ACVA",
    "ADAM", "ADC", "ADCT", "ADEA", "ADIG", "ADMA", "ADNT", "ADPT", "ADRO", "ADT",
    "ADTN", "ADUS", "ADV", "AEBI", "AEHR", "AEIS", "AEO", "AES", "AESI", "AEVA",
    "AFG", "AFRI", "AFRM", "AGCO", "AGEN", "AGIO", "AGL", "AGM", "AGNC", "AGNT",
    "AGO", "AGX", "AGYS", "AHCO", "AHR", "AHRT", "AI", "AII", "AIN", "AIOT",
    "AIP", "AIR", "AIRJ", "AIRO", "AIRS", "AIT", "AIZ", "AKBA", "AKE", "AKR",
    "AKTS", "ALB", "ALCO", "ALEC", "ALG", "ALGM", "ALGT", "ALH", "ALHC", "ALK",
    "ALKS", "ALKT", "ALLE", "ALLO", "ALLY", "ALM", "ALMR", "ALMS", "ALMU", "ALNT",
    "ALOY", "ALRM", "ALRS", "ALSN", "ALT", "ALTG", "ALTI", "ALTO", "ALX", "ALXO",
    "AM", "AMAL", "AMBA", "AMBP", "AMBQ", "AMC", "AMCX", "AMG", "AMH", "AMKR",
    "AMLX", "AMN", "AMPH", "AMPL", "AMPX", "AMPY", "AMR", "AMRC", "AMRX", "AMSC",
    "AMSF", "AMTB", "AMTM", "AMTX", "AN", "ANAB", "ANDE", "ANF", "ANGI", "ANGO",
    "ANIK", "ANIP", "ANNX", "ANRO", "ANTX", "AOMR", "AORT", "AOS", "AOSL", "AP",
    "APA", "APAM", "APC", "APEI", "APG", "APGE", "APLD", "APLE", "APOG", "APPF",
    "APPN", "APPS", "AQST", "AR", "ARCB", "ARCT", "ARDT", "ARDX", "ARE", "AREC",
    "ARHS", "ARKO", "ARL", "ARLO", "ARMK", "ARMP", "AROC", "AROW", "ARQT", "ARR",
    "ARRY", "ARTV", "ARVN", "ARW", "ARWR", "ARX", "AS", "ASAN", "ASB", "ASC",
    "ASH", "ASIC", "ASIX", "ASLE", "ASMB", "ASND", "ASO", "ASPI", "ASPN", "ASST",
    "ASTE", "ASTH", "ASUR", "ASYS", "ATAI", "ATEC", "ATEN", "ATEX", "ATI", "ATKR",
    "ATLC", "ATLO", "ATMU", "ATNI", "ATOM", "ATR", "ATRC", "ATRO", "AUB", "AUGO",
    "AUPH", "AUR", "AURA", "AVA", "AVAH", "AVAV", "AVBC", "AVBH", "AVBP", "AVEX",
    "AVIR", "AVLN", "AVNT", "AVNW", "AVO", "AVPT", "AVR", "AVT", "AVTR", "AVTX",
    "AVXL", "AVY", "AWI", "AWR", "AX", "AXGN", "AXS", "AXSM", "AXTA", "AXTI",
    "AYI", "AZTA", "AZZ", "BAH", "BALY", "BANC", "BAND", "BANF", "BANR", "BATRA",
    "BATRK", "BAX", "BBAI", "BBCP", "BBIO", "BBNX", "BBSI", "BBT", "BBUC", "BBW",
    "BBWI", "BC", "BCAL", "BCAX", "BCBP", "BCC", "BCML", "BCO", "BCPC", "BCRX",
    "BDC", "BDN", "BDTX", "BEAM", "BELFA", "BELFB", "BEN", "BEPC", "BETA", "BETR",
    "BFA", "BFAM", "BFB", "BFC", "BFH", "BFLY", "BFS", "BFST", "BGC", "BGS",
    "BH", "BHA", "BHB", "BHE", "BHF", "BHR", "BHRB", "BHVN", "BILL", "BIO",
    "BIOA", "BIPC", "BIRK", "BJ", "BJRI", "BKD", "BKE", "BKH", "BKKT", "BKSY",
    "BKTI", "BKU", "BKV", "BL", "BLBD", "BLDR", "BLFS", "BLKB", "BLMN", "BLND",
    "BLSH", "BLX", "BLZE", "BMBL", "BMI", "BMNR", "BMRC", "BMRN", "BNAI", "BNED",
    "BNL", "BNTC", "BOBS", "BOC", "BOH", "BOKF", "BOOT", "BORR", "BOW", "BOX",
    "BPOP", "BPRN", "BRBR", "BRBS", "BRCB", "BRCC", "BRKR", "BROS", "BRSL", "BRSP",
    "BRT", "BRX", "BRZE", "BSRR", "BSVN", "BSY", "BTBT", "BTDR", "BTSG", "BTU",
    "BULL", "BUR", "BUSE", "BV", "BVFL", "BVS", "BW", "BWA", "BWB", "BWFG",
    "BWIN", "BWMN", "BWXT", "BXC", "BXMT", "BXP", "BY", "BYD", "BZAI", "BZH",
    "CABA", "CABO", "CAC", "CACC", "CACI", "CADL", "CAG", "CAI", "CAKE", "CAL",
    "CALM", "CALX", "CALY", "CAMP", "CAPR", "CAR", "CARE", "CARG", "CARL", "CARS",
    "CART", "CASH", "CASS", "CATX", "CATY", "CAVA", "CBAN", "CBC", "CBFV", "CBIO",
    "CBK", "CBL", "CBLL", "CBNA", "CBNK", "CBRL", "CBSH", "CBT", "CBU", "CBZ",
    "CC", "CCB", "CCBG", "CCC", "CCCC", "CCK", "CCNE", "CCO", "CCOI", "CCS",
    "CCSI", "CD", "CDE", "CDNA", "CDNL", "CDP", "CDRE", "CDXS", "CDZI", "CE",
    "CECO", "CELC", "CELH", "CENT", "CENTA", "CENX", "CERS", "CERT", "CEVA", "CFBK",
    "CFFI", "CFFN", "CFR", "CG", "CGEM", "CGNX", "CGON", "CHCI", "CHCO", "CHCT",
    "CHDN", "CHE", "CHEF", "CHH", "CHMG", "CHPT", "CHRD", "CHRS", "CHRW", "CHWY",
    "CHYM", "CIA", "CIFR", "CIM", "CIVB", "CIX", "CLB", "CLBK", "CLDT", "CLDX",
    "CLF", "CLFD", "CLH", "CLMB", "CLMT", "CLNE", "CLOV", "CLPT", "CLSK", "CLVT",
    "CLW", "CLX", "CLYM", "CMC", "CMCL", "CMCO", "CMDB", "CMP", "CMPR", "CMPX",
    "CMRC", "CMRE", "CMT", "CMTG", "CMTV", "CNDT", "CNK", "CNM", "CNMD", "CNNE",
    "CNO", "CNOB", "CNR", "CNS", "CNTB", "CNTN", "CNTX", "CNX", "CNXC", "CNXN",
    "COCO", "CODI", "COFS", "COGT", "COHU", "COKE", "COLB", "COLD", "COLL", "COLM",
    "COMP", "CON", "CORT", "CORZ", "COSO", "COTY", "COUR", "CPB", "CPF", "CPK",
    "CPRI", "CPS", "CPSS", "CPT", "CR", "CRAI", "CRBG", "CRBP", "CRBU", "CRC",
    "CRCT", "CRDA", "CRGY", "CRI", "CRK", "CRL", "CRMD", "CRML", "CRNC", "CRNX",
    "CROX", "CRS", "CRSP", "CRSR", "CRUS", "CRVL", "CRVS", "CSIQ", "CSR", "CSTL",
    "CSTM", "CSV", "CSW", "CTBI", "CTEV", "CTGO", "CTKB", "CTMX", "CTNM", "CTO",
    "CTOS", "CTRE", "CTRI", "CTRN", "CTS", "CUBE", "CUBI", "CURB", "CURI", "CURV",
    "CUZ", "CV", "CVBF", "CVCO", "CVEO", "CVGI", "CVI", "CVLG", "CVLT", "CVRX",
    "CVSA", "CWBC", "CWCO", "CWEN", "CWH", "CWK", "CWST", "CWT", "CXDO", "CXM",
    "CXT", "CXW", "CYH", "CYRX", "CYTK", "CZFS", "CZNC", "CZR", "CZWI", "DAKT",
    "DAN", "DAR", "DAVE", "DBD", "DBI", "DBRG", "DBX", "DC", "DCH", "DCI",
    "DCO", "DCOM", "DCTH", "DDD", "DDS", "DEA", "DEC", "DEI", "DFH", "DFIN",
    "DFTX", "DGICA", "DGII", "DHC", "DHT", "DIBS", "DIN", "DINO", "DIOD", "DJCO",
    "DJT", "DK", "DKS", "DLB", "DLO", "DLX", "DMAC", "DMC", "DMRA", "DMRC",
    "DNA", "DNLI", "DNOW", "DNTH", "DNUT", "DOC", "DOCN", "DOCS", "DOCU", "DOLE",
    "DOMO", "DORM", "DOUG", "DOX", "DPZ", "DRH", "DRS", "DRUG", "DRVN", "DSGN",
    "DSGR", "DSP", "DT", "DTIL", "DTM", "DUOL", "DUOT", "DV", "DVA", "DX",
    "DXC", "DXPE", "DY", "DYN", "EAF", "EAT", "EBC", "EBF", "EBMT", "EBS",
    "ECBK", "ECG", "ECPG", "ECVT", "EDIT", "EE", "EEFT", "EFC", "EFOR", "EFSC",
    "EFSI", "EG", "EGAN", "EGBN", "EGHT", "EGP", "EGY", "EHC", "EIG", "EIKN",
    "ELA", "ELAN", "ELDN", "ELE", "ELF", "ELMD", "ELMT", "ELS", "ELTX", "ELVN",
    "EMBC", "EMN", "ENOV", "ENPH", "ENR", "ENS", "ENSG", "ENTA", "ENVA", "ENVX",
    "EOLS", "EOSE", "EPAC", "EPAM", "EPC", "EPM", "EPR", "EPRT", "EPSN", "EQBK",
    "EQH", "ERAS", "ERII", "ESAB", "ESCA", "ESE", "ESI", "ESNT", "ESOA", "ESP",
    "ESQ", "ESRT", "ESTA", "ESTC", "ETD", "ETON", "ETSY", "EU", "EVC", "EVCM",
    "EVER", "EVEX", "EVGO", "EVH", "EVI", "EVLV", "EVMN", "EVR", "EVTC", "EWBC",
    "EWTX", "EXEL", "EXLS", "EXP", "EXPO", "EXTR", "EYE", "EYPT", "FA", "FAF",
    "FBIN", "FBIZ", "FBK", "FBLA", "FBNC", "FBP", "FBRT", "FBRX", "FBYD", "FC",
    "FCAP", "FCBC", "FCCO", "FCEL", "FCF", "FCFS", "FCN", "FCPT", "FDBC", "FDMT",
    "FDS", "FEIM", "FELE", "FENC", "FET", "FF", "FFBC", "FFIN", "FFIV", "FG",
    "FGBI", "FHB", "FHN", "FHTX", "FIBK", "FIG", "FIGR", "FIGS", "FINW", "FIP",
    "FISI", "FIVE", "FIVN", "FIZZ", "FJET", "FLG", "FLGT", "FLNC", "FLNG", "FLO",
    "FLOC", "FLR", "FLS", "FLWS", "FLXS", "FLY", "FLYW", "FLYX", "FMAO", "FMBH",
    "FMC", "FMNB", "FNB", "FND", "FNKO", "FNLC", "FNRN", "FOA", "FOR", "FORM",
    "FOSL", "FOUR", "FOXF", "FPI", "FPS", "FR", "FRAF", "FRBA", "FRD", "FRHC",
    "FRME", "FRMI", "FROG", "FRPH", "FRPT", "FRSH", "FRST", "FRT", "FSBC", "FSBW",
    "FSLY", "FSS", "FSTR", "FSUN", "FTDR", "FTK", "FTRE", "FUBO", "FUL", "FULC",
    "FULT", "FUN", "FUNC", "FVCB", "FVR", "FWDI", "FWRD", "FWRG", "FXNC", "G",
    "GABC", "GALT", "GAP", "GATX", "GBCI", "GBFH", "GBTG", "GBX", "GCBC", "GCMG",
    "GCO", "GCT", "GDDY", "GDOT", "GDYN", "GEF", "GEFB", "GEMI", "GEN", "GENB",
    "GENC", "GENI", "GEO", "GERN", "GEVO", "GFF", "GFL", "GGG", "GH", "GHC",
    "GHM", "GIC", "GIII", "GKOS", "GL", "GLIBA", "GLIBK", "GLNG", "GLOB", "GLPI",
    "GLRE", "GLSI", "GLUE", "GLXY", "GME", "GMED", "GNE", "GNK", "GNL", "GNRC",
    "GNTX", "GNW", "GO", "GOGO", "GOLD", "GOLF", "GOOD", "GPGI", "GPI", "GPK",
    "GPOR", "GPRE", "GPRO", "GRAL", "GRBK", "GRC", "GRDN", "GRND", "GRNT", "GRPN",
    "GSAT", "GSBC", "GSHD", "GSIT", "GSM", "GT", "GTES", "GTLB", "GTM", "GTN",
    "GTX", "GTXI", "GTY", "GVA", "GWRE", "GWRS", "GXO", "GYRE", "H", "HAE",
    "HAFC", "HALO", "HAPN", "HAS", "HASI", "HAYW", "HBB", "HBCP", "HBNC", "HBT",
    "HCC", "HCI", "HCKT", "HCSG", "HDSN", "HE", "HELE", "HFWA", "HG", "HGV",
    "HHH", "HIFS", "HII", "HIMS", "HIPO", "HIW", "HL", "HLF", "HLI", "HLIO",
    "HLIT", "HLLY", "HLMN", "HLNE", "HLX", "HMH", "HMN", "HNGE", "HNI", "HNRG",
    "HNST", "HNVR", "HOG", "HOMB", "HOPE", "HOV", "HP", "HPK", "HPP", "HQI",
    "HQY", "HR", "HRB", "HRI", "HRL", "HRMY", "HROW", "HRTG", "HRTX", "HSHP",
    "HSIC", "HST", "HSTM", "HTB", "HTFL", "HTH", "HTLD", "HTO", "HTZ", "HUBG",
    "HUBS", "HUN", "HURN", "HUT", "HVT", "HWBK", "HWC", "HWKN", "HXL", "HY",
    "HYLN", "HYMC", "HYPR", "HZO", "IART", "IBCP", "IBEX", "IBOC", "IBP", "IBRX",
    "IBTA", "ICFI", "ICHR", "ICUI", "IDA", "IDCC", "IDN", "IDR", "IDT", "IDYA",
    "IE", "IESC", "IHRT", "III", "IIIN", "IIIV", "IIPR", "IKT", "ILPT", "IMAX",
    "IMKTA", "IMMR", "IMMX", "IMNM", "IMRX", "IMVT", "IMXI", "INBK", "INBX", "INDB",
    "INDI", "INDV", "INFQ", "INFU", "INGM", "INGN", "INGR", "INH", "INN", "INNV",
    "INOD", "INR", "INSE", "INSG", "INSP", "INSW", "INTA", "INTT", "INV", "INVA",
    "INVX", "IONQ", "IONS", "IOSP", "IOVA", "IPAR", "IPGP", "IPI", "IPSC", "IRD",
    "IRDM", "IREN", "IRMD", "IRON", "IRT", "IRTC", "IRWD", "ISBA", "ISSC", "ISTR",
    "IT", "ITGR", "ITIC", "ITRI", "ITT", "IVR", "IVT", "IVVD", "IVZ", "JACK",
    "JAKK", "JAN", "JANX", "JAZZ", "JBGS", "JBI", "JBIO", "JBLU", "JBS", "JBSS",
    "JBTM", "JCAP", "JEF", "JHX", "JILL", "JJSF", "JKHY", "JLL", "JMSB", "JOBY",
    "JOE", "JOUT", "JRVR", "JXN", "KAI", "KALU", "KBH", "KBR", "KD", "KE",
    "KEEL", "KELYA", "KEX", "KFRC", "KFY", "KGEI", "KGS", "KIDS", "KIM", "KINS",
    "KLC", "KLIC", "KLRA", "KLTR", "KMPR", "KMT", "KMTS", "KMX", "KN", "KNF",
    "KNSA", "KNSL", "KNTK", "KNX", "KOD", "KODK", "KOP", "KOPN", "KOS", "KPTI",
    "KRC", "KREF", "KRG", "KRMD", "KRMN", "KRNY", "KRO", "KROS", "KRRO", "KRT",
    "KRUS", "KRYS", "KSS", "KTB", "KTOS", "KURA", "KVHI", "KVYO", "KWR", "KWY",
    "KYMR", "KYTX", "LAD", "LADR", "LAMR", "LAND", "LARK", "LASR", "LAUR", "LAW",
    "LAZ", "LBRDA", "LBRDK", "LBRT", "LBRX", "LBTYA", "LBTYK", "LCID", "LCII", "LCNB",
    "LCTX", "LCUT", "LDI", "LE", "LEA", "LECO", "LEE", "LEG", "LEGH", "LENZ",
    "LEU", "LFCR", "LFMD", "LFST", "LFUS", "LGIH", "LGN", "LGND", "LIF", "LILA",
    "LILAK", "LINC", "LIND", "LINE", "LION", "LIVN", "LKFN", "LKQ", "LLYVA", "LLYVK",
    "LMAT", "LMB", "LMND", "LMNR", "LMRI", "LNC", "LNN", "LNTH", "LOAR", "LOB",
    "LOCO", "LODE", "LOPE", "LOVE", "LPG", "LPTH", "LPX", "LQDA", "LQDT", "LRMR",
    "LRN", "LSCC", "LSTR", "LTBR", "LTC", "LTH", "LTRX", "LUCD", "LUMN", "LUNR",
    "LVWR", "LW", "LWAY", "LWLG", "LXEO", "LXFR", "LXP", "LXRX", "LXU", "LYEL",
    "LYFT", "LYTS", "LZ", "LZB", "LZM", "M", "MAC", "MAGN", "MAMA", "MAN",
    "MANE", "MANH", "MARA", "MASS", "MAT", "MATV", "MATW", "MATX", "MAX", "MAZE",
    "MBC", "MBI", "MBIN", "MBUU", "MBWM", "MBX", "MC", "MCB", "MCBS", "MCFT",
    "MCHB", "MCRI", "MCS", "MCY", "MD", "MDGL", "MDU", "MDWD", "MDXG", "MEC",
    "MEDP", "MEI", "METC", "METCB", "MFA", "MFIN", "MFP", "MG", "MGEE", "MGM",
    "MGNI", "MGNX", "MGPI", "MGRC", "MGTX", "MGY", "MH", "MHK", "MHO", "MIAX",
    "MIDD", "MIR", "MIRM", "MITK", "MITT", "MKSI", "MKTW", "MKTX", "MLAB", "MLI",
    "MLKN", "MLP", "MLR", "MLYS", "MMED", "MMI", "MMS", "MMSI", "MNKD", "MNPR",
    "MNRO", "MNSB", "MNTK", "MNTN", "MOD", "MOGA", "MOH", "MORN", "MOS", "MOV",
    "MP", "MPAA", "MPB", "MPLT", "MPT", "MPTI", "MQ", "MRAM", "MRBK", "MRCY",
    "MRP", "MRTN", "MRVI", "MRX", "MSA", "MSBI", "MSEX", "MSGE", "MSGS", "MSM",
    "MTCH", "MTDR", "MTG", "MTH", "MTN", "MTRN", "MTRX", "MTSI", "MTUS", "MTW",
    "MTX", "MUR", "MUSA", "MUX", "MVBF", "MVST", "MWA", "MWH", "MXL", "MYE",
    "MYFW", "MYGN", "MYRG", "MZTI", "NABL", "NAGE", "NAT", "NATH", "NATL", "NATR",
    "NAUT", "NAVI", "NAVN", "NB", "NBBK", "NBHC", "NBIX", "NBN", "NBR", "NBTB",
    "NC", "NCLH", "NCMI", "NCNO", "NDSN", "NE", "NECB", "NEO", "NEOG", "NERV",
    "NESR", "NEU", "NEWT", "NEXN", "NEXT", "NFG", "NG", "NGNE", "NGS", "NGVC",
    "NGVT", "NHC", "NHI", "NHP", "NI", "NIC", "NIQ", "NJR", "NKSH", "NKTR",
    "NKTX", "NL", "NLOP", "NLY", "NMAX", "NMIH", "NMRA", "NMRK", "NN", "NNE",
    "NNI", "NNN", "NODK", "NOG", "NOV", "NOVT", "NP", "NPB", "NPCE", "NPK",
    "NPKI", "NPO", "NPWR", "NRC", "NRDS", "NREF", "NRGV", "NRIM", "NRIX", "NSIT",
    "NSP", "NSSC", "NTB", "NTCT", "NTGR", "NTLA", "NTNX", "NTST", "NUAI", "NUS",
    "NUTX", "NUVB", "NVAX", "NVCR", "NVCT", "NVEC", "NVGS", "NVRI", "NVST", "NVT",
    "NVTS", "NWBI", "NWE", "NWFL", "NWL", "NWN", "NWPX", "NWS", "NWSA", "NX",
    "NXDR", "NXDT", "NXH", "NXRT", "NXST", "NXT", "NYT", "OABI", "OBIO", "OBK",
    "OBT", "OC", "OCFC", "OCGN", "OCUL", "ODC", "ODD", "OEC", "OFG", "OFIX",
    "OFLX", "OFRM", "OGE", "OGN", "OGS", "OHI", "OI", "OII", "OIS", "OKLO",
    "OKUR", "OLED", "OLLI", "OLMA", "OLN", "OLP", "OMCL", "OMDA", "OMER", "OMF",
    "ONB", "ONDS", "ONEW", "ONIT", "ONL", "ONT", "ONTO", "OOMA", "OPAL", "OPBK",
    "OPCH", "OPEN", "OPFI", "OPK", "OPLN", "OPRT", "OPTU", "OPTX", "ORA", "ORC",
    "ORGO", "ORI", "ORIC", "ORKA", "ORMP", "ORN", "ORRF", "OSBC", "OSCR", "OSG",
    "OSIS", "OSK", "OSPN", "OSS", "OSUR", "OSW", "OTTR", "OUST", "OUT", "OVBC",
    "OVID", "OVLY", "OVV", "OXM", "OZK", "PACB", "PACK", "PACS", "PAG", "PAGS",
    "PAHC", "PAL", "PALI", "PAMT", "PANL", "PAR", "PARR", "PATH", "PATK", "PAX",
    "PAY", "PAYC", "PAYO", "PAYS", "PB", "PBF", "PBFS", "PBH", "PBI", "PBYI",
    "PCB", "PCOR", "PCRX", "PCT", "PCTY", "PCVX", "PCYO", "PD", "PDEX", "PDFS",
    "PDLB", "PDLI", "PDM", "PDYN", "PEB", "PEBK", "PEBO", "PECO", "PEGA", "PEN",
    "PENG", "PENN", "PESI", "PFBC", "PFGC", "PFIS", "PFS", "PFSI", "PGC", "PGEN",
    "PGNY", "PHAT", "PHIN", "PHR", "PI", "PII", "PINE", "PINS", "PIPR", "PJT",
    "PK", "PKBK", "PKE", "PKG", "PKOH", "PL", "PLAB", "PLAY", "PLBC", "PLBY",
    "PLGO", "PLMR", "PLNT", "PLOW", "PLPC", "PLSE", "PLTK", "PLUG", "PLUS", "PLX",
    "PLXS", "PMT", "PMTS", "PNFP", "PNR", "PNRG", "PNTG", "PNW", "PODD", "POOL",
    "POR", "POST", "POWI", "POWL", "POWW", "PPC", "PPHC", "PPIH", "PPLI", "PPTA",
    "PR", "PRAA", "PRAX", "PRCH", "PRCT", "PRDO", "PRG", "PRGO", "PRGS", "PRI",
    "PRIM", "PRK", "PRKS", "PRLB", "PRLD", "PRM", "PRMB", "PRME", "PROK", "PRSU",
    "PRTA", "PRTH", "PRVA", "PSFE", "PSIX", "PSMT", "PSN", "PSNL", "PSTL", "PTCT",
    "PTEN", "PTGX", "PTLO", "PTON", "PTRN", "PUBM", "PUMP", "PURR", "PVH", "PVLA",
    "PWP", "PXED", "PZZA", "QBTS", "QCRH", "QDEL", "QGEN", "QLYS", "QNST", "QRVO",
    "QS", "QTRX", "QTWO", "QUAD", "QUBT", "QUIK", "QXO", "R", "RAIL", "RAL",
    "RAMP", "RAPP", "RARE", "RBB", "RBBN", "RBC", "RBCAA", "RBKB", "RBRK", "RC",
    "RCAT", "RCKT", "RCKY", "RCMT", "RCUS", "RDN", "RDNT", "RDNW", "RDVT", "RDW",
    "RDZN", "REAL", "REAX", "REFI", "REG", "REI", "RELL", "RELY", "RENT", "REPL",
    "REPX", "RES", "REX", "REXR", "REYN", "REZI", "RFIL", "RGA", "RGCO", "RGEN",
    "RGLD", "RGNX", "RGR", "RGTI", "RH", "RHI", "RHLD", "RHP", "RICK", "RIG",
    "RIGL", "RILY", "RIOT", "RITM", "RIVN", "RJET", "RL", "RLAY", "RLGT", "RLI",
    "RLJ", "RLMD", "RM", "RMAX", "RMBI", "RMBS", "RMNI", "RMR", "RNA", "RNAC",
    "RNG", "RNGR", "RNR", "RNST", "ROAD", "ROCK", "ROG", "ROIV", "ROKU", "ROOT",
    "RPAY", "RPC", "RPD", "RPM", "RR", "RRBI", "RRC", "RRR", "RRX", "RS",
    "RSI", "RSVR", "RUM", "RUN", "RUSHA", "RUSHB", "RVLV", "RVTY", "RWT", "RXO",
    "RXRX", "RXST", "RXT", "RYAM", "RYAN", "RYN", "RYTM", "RYZ", "RZLT", "S",
    "SABR", "SABS", "SAFE", "SAFT", "SAH", "SAIA", "SAIC", "SAIL", "SAM", "SAMG",
    "SANA", "SANM", "SARO", "SATL", "SB", "SBC", "SBCF", "SBET", "SBGI", "SBH",
    "SBMT", "SBRA", "SBSI", "SBT", "SCHL", "SCI", "SCL", "SCSC", "SD", "SDGR",
    "SDRL", "SEB", "SEG", "SEI", "SEIC", "SENEA", "SENS", "SEPN", "SERV", "SES",
    "SEVN", "SEZL", "SF", "SFBS", "SFD", "SFIX", "SFL", "SFM", "SFNC", "SFST",
    "SG", "SGC", "SGHC", "SGHT", "SGI", "SGMT", "SGP", "SGRY", "SHAK", "SHAZ",
    "SHBI", "SHC", "SHEN", "SHLS", "SHO", "SHOE", "SHOO", "SI", "SIBN", "SIDU",
    "SIG", "SIGA", "SIGI", "SION", "SIRI", "SITC", "SITE", "SITM", "SJM", "SKT",
    "SKWD", "SKY", "SKYH", "SKYW", "SLAB", "SLDB", "SLDE", "SLDP", "SLG", "SLGN",
    "SLM", "SLNH", "SLP", "SLS", "SLVM", "SM", "SMA", "SMBC", "SMBK", "SMC",
    "SMG", "SMHI", "SMID", "SMMT", "SMP", "SMPL", "SMR", "SMRT", "SMTC", "SMTI",
    "SN", "SNA", "SND", "SNDA", "SNDR", "SNDX", "SNEX", "SNFCA", "SNX", "SOC",
    "SOFI", "SOLV", "SON", "SONO", "SOUN", "SPB", "SPCE", "SPFI", "SPHR", "SPIR",
    "SPNT", "SPOK", "SPRB", "SPRY", "SPSC", "SPT", "SPXC", "SR", "SRBK", "SRCE",
    "SRI", "SRPT", "SRRK", "SRTA", "SRZN", "SSB", "SSD", "SSP", "SSRM", "SSTK",
    "ST", "STAA", "STAG", "STBA", "STC", "STEP", "STGW", "STLN", "STNE", "STNG",
    "STOK", "STRA", "STRL", "STRO", "STRT", "STRW", "STRZ", "STTK", "STUB", "STWD",
    "STXS", "SUPN", "SVC", "SVCO", "SVRA", "SVV", "SWBI", "SWIM", "SWK", "SWKS",
    "SWMR", "SWX", "SXC", "SXI", "SXT", "SYBT", "SYNA", "SYRE", "TALK", "TALO",
    "TAP", "TARA", "TARS", "TATT", "TAYD", "TBBK", "TBCH", "TBI", "TBLA", "TBPH",
    "TCBI", "TCBK", "TCBX", "TCI", "TCMD", "TCX", "TDAY", "TDC", "TDOC", "TDS",
    "TDUP", "TDW", "TE", "TECH", "TECX", "TEM", "TENB", "TENX", "TEX", "TFIN",
    "TFSL", "TFX", "TG", "TGLS", "TGTX", "TH", "THC", "THFF", "THG", "THO",
    "THRD", "THRM", "THRY", "TIC", "TIGO", "TILE", "TIPT", "TITN", "TK", "TKNO",
    "TKR", "TLN", "TLS", "TLSI", "TMDX", "TMP", "TNC", "TNDM", "TNET", "TNGX",
    "TNK", "TNL", "TNXP", "TOL", "TOWN", "TOYO", "TPB", "TPC", "TPG", "TRAK",
    "TRAX", "TRC", "TRDA", "TREE", "TREX", "TRIP", "TRMK", "TRN", "TRNO", "TRNS",
    "TRON", "TROX", "TRS", "TRST", "TRTX", "TRUP", "TRVI", "TSBK", "TSEOQ", "TSHA",
    "TSSI", "TTAM", "TTAN", "TTC", "TTD", "TTEK", "TTGT", "TTI", "TTMI", "TVTX",
    "TWI", "TWIN", "TWO", "TWST", "TXG", "TXNM", "TXRH", "TXT", "TYGO", "TYRA",
    "U", "UA", "UAA", "UAMY", "UBSI", "UCB", "UCTT", "UDR", "UE", "UEC",
    "UFCS", "UFPI", "UFPT", "UGI", "UHAL", "UHALB", "UHS", "UHT", "UIS", "ULCC",
    "ULH", "UMAC", "UMBF", "UMH", "UNCY", "UNF", "UNFI", "UNIT", "UNM", "UNTY",
    "UP", "UPB", "UPBD", "UPST", "UPWK", "URBN", "URG", "URGN", "USAR", "USAU",
    "USCB", "USFD", "USGO", "USLM", "USNA", "USPH", "UTI", "UTL", "UTMD", "UTZ",
    "UUUU", "UVE", "UVSP", "UVV", "UWMC", "VABK", "VAC", "VAL", "VALU", "VATE",
    "VC", "VCEL", "VCTR", "VCYT", "VECO", "VEL", "VELO", "VENU", "VERA", "VERI",
    "VERX", "VFC", "VGNT", "VGZ", "VHI", "VIA", "VIAV", "VICR", "VIR", "VIRT",
    "VISN", "VITL", "VKTX", "VLGEA", "VLY", "VMD", "VMI", "VNDA", "VNO", "VNOM",
    "VNT", "VOR", "VOXR", "VOYA", "VOYG", "VPG", "VRDN", "VREX", "VRNS", "VRRM",
    "VRTS", "VSAT", "VSEC", "VSH", "VSNT", "VSTM", "VSTS", "VSXY", "VTOL", "VTRS",
    "VTS", "VUZI", "VVV", "VVX", "VYGR", "VYX", "W", "WABC", "WAFD", "WAL",
    "WASH", "WATT", "WAY", "WBS", "WBTN", "WCC", "WD", "WDFC", "WEAV", "WEN",
    "WERN", "WEST", "WEX", "WEYS", "WFRD", "WGO", "WGS", "WH", "WHD", "WHG",
    "WHR", "WHWK", "WINA", "WING", "WK", "WKC", "WLDN", "WLFC", "WLTH", "WLY",
    "WMK", "WMS", "WNC", "WNEB", "WOLF", "WOOF", "WOR", "WRBY", "WRLD", "WS",
    "WSBC", "WSBF", "WSC", "WSFS", "WSO", "WT", "WTBA", "WTFC", "WTI", "WTM",
    "WTRG", "WTS", "WTTR", "WU", "WULF", "WVE", "WWD", "WWW", "WYFI", "WYNN",
    "XE", "XENE", "XERS", "XFOR", "XHR", "XMAX", "XMTR", "XNCR", "XP", "XPEL",
    "XPER", "XPOF", "XPRO", "XRAY", "XRN", "XRX", "XZO", "YELP", "YETI", "YEXT",
    "YORW", "YOU", "YSS", "YSWY", "Z", "ZBIO", "ZBRA", "ZD", "ZENA", "ZETA",
    "ZG", "ZGN", "ZION", "ZIP", "ZNTL", "ZSQR", "ZUMZ", "ZURA", "ZVRA", "ZWS",
    "ZYME",
]
